### ISSUE TITLE
 AMQP Client connection has shut down unexpectedly, starting reconnect cycle

### ISSUE THREAD

**Issue by bobjana** [muoncore/photonlite#6]
Even though rabbitmq is running, photon complains that it's unable to connect:

```
7/11/2017 9:31:26 AM2017-07-11 07:31:26.450 ERROR 8 --- [42.239.116:5672] i.m.e.a.r.RabbitMq09ClientAmqpConnection : AMQP Client connection has shut down unexpectedly, starting reconnect cycle
7/11/2017 9:31:26 AM2017-07-11 07:31:26.450  WARN 8 --- [      channel-4] nClusterAwareTrackingSubscriptionManager : NewtonEvent subscription has ended, will attempt to reconnect in 5000ms
7/11/2017 9:31:26 AM2017-07-11 07:31:26.454  INFO 8 --- [      Thread-49] i.m.e.a.r.RabbitMq09ClientAmqpConnection : Connecting to AMQP broker using url: amqp://guest:guest@rabbitmq
7/11/2017 9:31:31 AM2017-07-11 07:31:31.454  INFO 8 --- [      channel-4] nClusterAwareTrackingSubscriptionManager : Subscribing from index 85 to event stream SAGA_LIFECYCLE_STREAM 'saga-lifecycle'
7/11/2017 9:31:31 AM2017-07-11 07:31:31.456 ERROR 8 --- [      channel-4] nClusterAwareTrackingSubscriptionManager : Error in subscription
7/11/2017 9:31:31 AM
7/11/2017 9:31:31 AMio.muoncore.exception.MuonException: Connection lost to remote service, the channel has shut down due to a transport failure
7/11/2017 9:31:31 AM	at io.muoncore.protocol.reactivestream.client.ReactiveStreamClientProtocol.handleMessage(ReactiveStreamClientProtocol.java:114)
7/11/2017 9:31:31 AM	at io.muoncore.channel.impl.WiretapChannel$2.lambda$send$0(WiretapChannel.java:64)
7/11/2017 9:31:31 AM	at io.muoncore.transport.client.RingBufferLocalDispatcher.route(RingBufferLocalDispatcher.java:404)
7/11/2017 9:31:31 AM	at io.muoncore.transport.client.RingBufferLocalDispatcher$SingleThreadTask.run(RingBufferLocalDispatcher.java:297)
7/11/2017 9:31:31 AM	at io.muoncore.transport.client.RingBufferLocalDispatcher$3.onEvent(RingBufferLocalDispatcher.java:171)
7/11/2017 9:31:31 AM	at io.muoncore.transport.client.RingBufferLocalDispatcher$3.onEvent(RingBufferLocalDispatcher.java:168)
7/11/2017 9:31:31 AM	at reactor.jarjar.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
7/11/2017 9:31:31 AM	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
7/11/2017 9:31:31 AM	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
7/11/2017 9:31:31 AM	at java.lang.Thread.run(Thread.java:745)
7/11/2017 9:31:31 AM
```

**Comment by bobjana** [comment]
Mark (Cibecs) mentions that he has seen this a couple of times in our QA env, so will need to escalate this.

**Comment by daviddawson** [comment]
This is a client side/ newton log. 

Related to https://github.com/muoncore/newton/issues/58
https://github.com/muoncore/newton/issues/54
https://github.com/muoncore/newton/issues/40

**Comment by daviddawson** [comment]
Fixed in newton https://github.com/muoncore/newton/issues/58
